# Generated by Django 5.2 on 2025-04-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("common_name", models.CharField(max_length=1000, unique=True)),
                ("optimal_temperature_min", models.FloatField()),
                ("optimal_temperature_max", models.FloatField()),
                ("optimal_humidity_min", models.FloatField()),
                ("optimal_humidity_max", models.FloatField()),
                ("optimal_light_min", models.FloatField()),
                ("optimal_light_max", models.FloatField()),
                ("source", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("soil", "Soil Moisture"),
                            ("light", "Light Intensity"),
                            ("temp", "Temperature"),
                            ("humidity", "Humidity"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CropSuitabilityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_suitable", models.BooleanField()),
                ("message", models.TextField()),
                ("score", models.FloatField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="smartfarm.crop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartfarm.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
