# Generated by Django 5.2 on 2025-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfarm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="common_name",
            field=models.CharField(max_length=1000),
        ),
    ]
